repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        args: ['--line-length', '88', '--skip-string-normalization']

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1  
    hooks:
      - id: flake8
        language_version: python3
        args: 
          - '--max-line-length=88'
