dataset:
  data: ../AAU-P4-Gruppe3-MLOps/dataset
  s3_path: s3://aaumlopsp4/Dataset/cifar-10-batches-py/
  dvc_path: ../AAU-P4-Gruppe3-MLOps/dataset/cifar-10-batches-py.dvc
  script_path: ../datasets/cifar10_keras.py
  

model:
  script_path: ../models/optimized.py

wandb:
    project: MLOps

train:
  script_path: ../train/train_keras.py
  artifacts_path: ../artifacts/cifar10_opt/
  train_test_split: 0.8
  batch_size: 32
  epochs: 10
  lr: 0.001
  gamma: 0.5
  step_size: 5
  scheduler: steplr
  optimizer: adam
  num_workers: 1
  
data_augmentation:
  horizontal_flip: 0
  vertical_flip: 0
  brightness: 0
  contrast: 0
  saturation: 0
  hue: 0
  grayscale: 0
  rotation: [0,0]
  width_shift: 0
  height_shift: 0
  degrees: 0
  distortion_scale: 0
  resize: [32, 32]

  experiments:
  - name: experiment_1
    optimizer:
      initial_lr: 0.0001
    train:
      batch_size: 64
      epochs: 1000

  - name: experiment_2
    optimizer:
      initial_lr: 0.001
    train:
      batch_size: 128
      epochs: 500

  - name: experiment_3
    optimizer:
      initial_lr: 0.0005
    train:
      batch_size: 32
      epochs: 1500

  