stages:
  augment:
    cmd: python dataset/augment.py
    deps:
    - dataset/augment.py
    - dataset/original_data/cifar-10-batches-py
    outs:
    - dataset/augmented_data/cifar-10-batches-py
  model_org:
    cmd: python train.py
    deps:
    - config.yaml
    - modelstructure.py
    - requirements.txt
    - train.py
    - utils/dataloader.py
    - utils/utils.py
    outs:
    - models/model_org/config.json
    - models/model_org/model.onnx
  deepspeed_stage_1:
    cmd: deepspeed --num_gpus=1 train.py
    deps:
    - config.yaml
    - modelstructure.py
    - requirements.txt
    - train.py
    - utils/dataloader.py
    - utils/utils.py
    outs:
    - models/deepspeed_stage_1/config.json
    - models/deepspeed_stage_1/model.onnx
  deepspeed_stage_2:
    cmd: deepspeed --num_gpus=1 train.py
    deps:
    - config.yaml
    - modelstructure.py
    - requirements.txt
    - train.py
    - utils/dataloader.py
    - utils/utils.py
    outs:
    - models/deepspeed_stage_2/config.json
    - models/deepspeed_stage_2/model.onnx
