stages:
  augmented_data:
    cmd: python dataset/augment.py
    deps:
    - dataset/augment.py
    - dataset/original_data/cifar-10-batches-py
    outs:
    - dataset/augmented_data/cifar-10-batches-py
  model_org:
    cmd: python train.py
    deps:
    - config.yaml
    - dataset/original_data/cifar-10-batches-py
    - modelstructure.py
    - requirements.txt
    - train.py
    - utils/dataloader.py
    - utils/utils.py
    outs:
    - models/model_org/config.json
    - models/model_org/model.onnx
    frozen: true
  deepspeed_stage_1:
    cmd: deepspeed --num_gpus=1 train.py
    deps:
    - config.yaml
    - dataset/original_data/cifar-10-batches-py
    - modelstructure.py
    - requirements.txt
    - train.py
    - utils/dataloader.py
    - utils/utils.py
    outs:
    - models/deepspeed_stage_1/config.json
    - models/deepspeed_stage_1/model.onnx
    frozen: true
  deepspeed_stage_2:
    cmd: deepspeed --num_gpus=1 train.py
    deps:
    - config.yaml
    - dataset/original_data/cifar-10-batches-py
    - modelstructure.py
    - requirements.txt
    - train.py
    - utils/dataloader.py
    - utils/utils.py
    outs:
    - models/deepspeed_stage_2/config.json
    - models/deepspeed_stage_2/model.onnx
    frozen: true
  deepspeed_stage_3:
    cmd: deepspeed --num_gpus=1 train.py
    deps:
    - config.yaml
    - dataset/original_data/cifar-10-batches-py
    - modelstructure.py
    - requirements.txt
    - train.py
    - utils/dataloader.py
    - utils/utils.py
    outs:
    - models/deepspeed_stage_3/config.json
    - models/deepspeed_stage_3/model.onnx
    frozen: true
  quantize_stage_1:
    cmd: python Lecture4/quantize.py
    deps:
    - Lecture4/quantize.py
    - models/deepspeed_stage_1/model.onnx
    - requirements.txt
    outs:
    - models/deepspeed_stage_1/model_quantized.onnx
  quantize_stage_2:
    cmd: python Lecture4/quantize.py
    deps:
    - Lecture4/quantize.py
    - models/deepspeed_stage_2/model.onnx
    - requirements.txt
    outs:
    - models/deepspeed_stage_2/model_quantized.onnx
  quantize_stage_3:
    cmd: python Lecture4/quantize.py
    deps:
    - Lecture4/quantize.py
    - models/deepspeed_stage_3/model.onnx
    - requirements.txt
    outs:
    - models/deepspeed_stage_3/model_quantized.onnx
  quantize_model_org:
    cmd: python Lecture4/quantize.py
    deps:
    - Lecture4/quantize.py
    - models/model_org/model.onnx
    - requirements.txt
    outs:
    - models/model_org/model_quantized.onnx
